In [29]:
import pandas as pd
import datetime as dt

In [30]:
pd.set_option('display.max_rows',None)

In [31]:
account_transactions=pd.read_csv('/Users/aaronless/Desktop/Data Analysis Porfolio Projects/Other/Finance Project/Cleaned CSV Files/cleaned_data.csv')
account_transactions.head(50)

,account_id,credit_score,account_status,transaction_id,transaction_date,category,transaction_type,payment_method,status
0,NaN,NaN,NaN,100001,2022-05-19,Fees,Fee,ACH,Completed
1,10357.0,734.0,Active,100002,2025-01-13,Utilities,Payment,Credit Card,Completed
2,10140.0,600.0,Active,100003,2025-08-04,Entertainment,Payment,ACH,Completed
3,10049.0,765.0,Active,100004,28/03/2022,Healthcare,Payment,Credit Card,Completed
4,10544.0,452.0,Closed,100005,2022-10-19,Payroll/Salary,Deposit,ACH,Completed
5,10415.0,307.0,Active,100006,2025-10-19,Utilities,Payment,Debit Card,Completed
6,10481.0,331.0,Active,100007,25/09/2022,Entertainment,Payment,Debit Card,Failed
7,10519.0,363.0,Active,100008,2022-09-16,Insurance,Payment,Credit Card,Completed
8,10560.0,602.0,Active,100009,2024-02-05,Insurance,Payment,Check,Completed
9,10328.0,620.0,Active,100010,2022-11-18,Dining,Withdrawal,Debit Card,Completed
10,10636.0,756.0,Active,100011,2023-01-03,Healthcare,Payment,Check,Completed
11,10437.0,335.0,Active,100012,2023-06-11,Payroll/Salary,Deposit,ACH,Completed
12,NaN,NaN,NaN,100013,15/11/2024,Utilities,Payment,Debit Card,Completed
13,10385.0,679.0,Active,100014,2023-06-03,Healthcare,Payment,Credit Card,Completed
14,10168.0,319.0,Active,100015,2022-02-17,Fees,Fee,ACH,Failed
15,10447.0,387.0,Active,100016,2025-02-06,Utilities,Payment,Debit Card,Completed
16,10624.0,640.0,Active,100017,2024-03-11,Utilities,Payment,Check,Completed
17,10231.0,419.0,Active,100018,26/10/2024,Shopping,Payment,Debit Card,Completed
18,10249.0,659.0,Active,100019,2024-07-23,Dining,Withdrawal,Credit Card,Completed
19,10459.0,682.0,Active,100020,2023-07-15,Transfers,Transfer,ACH,Completed
20,10334.0,780.0,Closed,100021,2022-02-24,Rent,Payment,Wire Transfer,Completed
21,10061.0,837.0,Frozen,100022,2026-01-01,Healthcare,Payment,Credit Card,Completed
22,NaN,NaN,NaN,100023,2022-11-11,Healthcare,Payment,Debit Card,Completed
23,10648.0,319.0,Active,100024,2026-04-21,Entertainment,Payment,Credit Card,Completed
24,10375.0,826.0,Active,100025,2024-05-01,Insurance,Payment,Credit Card,Completed
25,10402.0,710.0,Active,100026,2023-03-27,Rent,Payment,Check,Completed
26,10065.0,753.0,Active,100027,2025-11-27,Transportation,Withdrawal,Cash,Completed
27,10458.0,573.0,Active,100028,2022-01-28,Entertainment,Payment,Credit Card,Completed
28,10648.0,319.0,Active,100029,2023-11-05,Utilities,Payment,Check,Completed
29,10513.0,568.0,Closed,100030,2024-02-21,Insurance,Payment,Credit Card,Completed
30,10271.0,714.0,Active,100031,2026-01-24,Healthcare,Payment,Credit Card,Completed
31,10293.0,696.0,Closed,100032,22/06/2024,Transportation,Withdrawal,Credit Card,Completed
32,NaN,NaN,NaN,100033,2024-02-08,Insurance,Payment,Check,Completed
33,10178.0,497.0,Active,100034,2024-09-29,Payroll/Salary,Deposit,ACH,Pending
34,10436.0,631.0,Active,100035,2024-05-18,Shopping,Withdrawal,Debit Card,Completed
35,NaN,NaN,NaN,100036,2026-04-28,Rent,Payment,Wire Transfer,Completed
36,10471.0,448.0,Active,100037,2022-07-02,Rent,Payment,NaN,Pending
37,NaN,NaN,NaN,100038,2024-06-01,Utilities,Payment,Debit Card,Completed
38,10468.0,756.0,Active,100039,2024-04-17,Healthcare,Payment,Check,Completed
39,10260.0,312.0,Active,100040,2022-03-27,Rent,Payment,Wire Transfer,Pending
40,10042.0,555.0,Active,100041,2022-04-28,Dining,Withdrawal,Credit Card,Completed
41,10436.0,631.0,Active,100042,31/08/2024,Insurance,Payment,ACH,Completed
42,10698.0,427.0,Active,100043,2024-02-09,Transfers,Transfer,Wire Transfer,Completed
43,10463.0,611.0,Active,100044,2024-08-14,Utilities,Payment,Debit Card,Completed
44,NaN,NaN,NaN,100045,2024-09-02,Transfers,Transfer,ACH,Completed
45,10416.0,732.0,Active,100046,2024-06-13,Entertainment,Payment,Debit Card,Completed
46,10077.0,448.0,Closed,100047,2025-04-23,Insurance,Payment,Check,NaN
47,10402.0,710.0,Active,100048,2023-03-25,Healthcare,Payment,Credit Card,Completed
48,10197.0,315.0,Active,100049,18/07/2026,Dining,Withdrawal,Cash,Completed
49,10363.0,722.0,Closed,100050,2025-10-20,Healthcare,Payment,Debit Card,Completed

In [35]:
account_transactions=account_transactions.dropna(subset=['account_id'])
account_transactions.head(50)

,account_id,credit_score,account_status,transaction_id,transaction_date,category,transaction_type,payment_method,status
1,10357.0,734.0,Active,100002,2025-01-13,Utilities,Payment,Credit Card,Completed
2,10140.0,600.0,Active,100003,2025-08-04,Entertainment,Payment,ACH,Completed
3,10049.0,765.0,Active,100004,28/03/2022,Healthcare,Payment,Credit Card,Completed
4,10544.0,452.0,Closed,100005,2022-10-19,Payroll/Salary,Deposit,ACH,Completed
5,10415.0,307.0,Active,100006,2025-10-19,Utilities,Payment,Debit Card,Completed
6,10481.0,331.0,Active,100007,25/09/2022,Entertainment,Payment,Debit Card,Failed
7,10519.0,363.0,Active,100008,2022-09-16,Insurance,Payment,Credit Card,Completed
8,10560.0,602.0,Active,100009,2024-02-05,Insurance,Payment,Check,Completed
9,10328.0,620.0,Active,100010,2022-11-18,Dining,Withdrawal,Debit Card,Completed
10,10636.0,756.0,Active,100011,2023-01-03,Healthcare,Payment,Check,Completed
11,10437.0,335.0,Active,100012,2023-06-11,Payroll/Salary,Deposit,ACH,Completed
13,10385.0,679.0,Active,100014,2023-06-03,Healthcare,Payment,Credit Card,Completed
14,10168.0,319.0,Active,100015,2022-02-17,Fees,Fee,ACH,Failed
15,10447.0,387.0,Active,100016,2025-02-06,Utilities,Payment,Debit Card,Completed
16,10624.0,640.0,Active,100017,2024-03-11,Utilities,Payment,Check,Completed
17,10231.0,419.0,Active,100018,26/10/2024,Shopping,Payment,Debit Card,Completed
18,10249.0,659.0,Active,100019,2024-07-23,Dining,Withdrawal,Credit Card,Completed
19,10459.0,682.0,Active,100020,2023-07-15,Transfers,Transfer,ACH,Completed
20,10334.0,780.0,Closed,100021,2022-02-24,Rent,Payment,Wire Transfer,Completed
21,10061.0,837.0,Frozen,100022,2026-01-01,Healthcare,Payment,Credit Card,Completed
23,10648.0,319.0,Active,100024,2026-04-21,Entertainment,Payment,Credit Card,Completed
24,10375.0,826.0,Active,100025,2024-05-01,Insurance,Payment,Credit Card,Completed
25,10402.0,710.0,Active,100026,2023-03-27,Rent,Payment,Check,Completed
26,10065.0,753.0,Active,100027,2025-11-27,Transportation,Withdrawal,Cash,Completed
27,10458.0,573.0,Active,100028,2022-01-28,Entertainment,Payment,Credit Card,Completed
28,10648.0,319.0,Active,100029,2023-11-05,Utilities,Payment,Check,Completed
29,10513.0,568.0,Closed,100030,2024-02-21,Insurance,Payment,Credit Card,Completed
30,10271.0,714.0,Active,100031,2026-01-24,Healthcare,Payment,Credit Card,Completed
31,10293.0,696.0,Closed,100032,22/06/2024,Transportation,Withdrawal,Credit Card,Completed
33,10178.0,497.0,Active,100034,2024-09-29,Payroll/Salary,Deposit,ACH,Pending
34,10436.0,631.0,Active,100035,2024-05-18,Shopping,Withdrawal,Debit Card,Completed
36,10471.0,448.0,Active,100037,2022-07-02,Rent,Payment,NaN,Pending
38,10468.0,756.0,Active,100039,2024-04-17,Healthcare,Payment,Check,Completed
39,10260.0,312.0,Active,100040,2022-03-27,Rent,Payment,Wire Transfer,Pending
40,10042.0,555.0,Active,100041,2022-04-28,Dining,Withdrawal,Credit Card,Completed
41,10436.0,631.0,Active,100042,31/08/2024,Insurance,Payment,ACH,Completed
42,10698.0,427.0,Active,100043,2024-02-09,Transfers,Transfer,Wire Transfer,Completed
43,10463.0,611.0,Active,100044,2024-08-14,Utilities,Payment,Debit Card,Completed
45,10416.0,732.0,Active,100046,2024-06-13,Entertainment,Payment,Debit Card,Completed
46,10077.0,448.0,Closed,100047,2025-04-23,Insurance,Payment,Check,NaN
47,10402.0,710.0,Active,100048,2023-03-25,Healthcare,Payment,Credit Card,Completed
48,10197.0,315.0,Active,100049,18/07/2026,Dining,Withdrawal,Cash,Completed
49,10363.0,722.0,Closed,100050,2025-10-20,Healthcare,Payment,Debit Card,Completed
50,10447.0,387.0,Active,100051,2022-10-09,Healthcare,Payment,Credit Card,Completed
51,10545.0,400.0,Active,100052,2022-04-26,Rent,Payment,Check,Failed
52,10269.0,716.0,Active,100053,2022-12-20,Transfers,Transfer,Wire Transfer,Completed
53,10100.0,448.0,Active,100054,2024-09-09,Transfers,Deposit,Wire Transfer,Completed
54,10227.0,773.0,Active,100055,2026-07-22,Payroll/Salary,Payment,ACH,Completed
55,10361.0,460.0,Active,100056,2026-03-23,Insurance,Payment,ACH,Completed
56,10207.0,516.0,Active,100057,2023-10-03,Groceries,Payment,Credit Card,Completed

In [38]:
account_transactions['transaction_date']=pd.to_datetime(account_transactions['transaction_date'],errors='coerce')
account_transactions['transaction_date'].head(50)

1    2025-01-13
2    2025-08-04
3    2022-03-28
4    2022-10-19
5    2025-10-19
6    2022-09-25
7    2022-09-16
8    2024-02-05
9    2022-11-18
10   2023-01-03
11   2023-06-11
13   2023-06-03
14   2022-02-17
15   2025-02-06
16   2024-03-11
17   2024-10-26
18   2024-07-23
19   2023-07-15
20   2022-02-24
21   2026-01-01
23   2026-04-21
24   2024-05-01
25   2023-03-27
26   2025-11-27
27   2022-01-28
28   2023-11-05
29   2024-02-21
30   2026-01-24
31   2024-06-22
33   2024-09-29
34   2024-05-18
36   2022-07-02
38   2024-04-17
39   2022-03-27
40   2022-04-28
41   2024-08-31
42   2024-02-09
43   2024-08-14
45   2024-06-13
46   2025-04-23
47   2023-03-25
48   2026-07-18
49   2025-10-20
50   2022-10-09
51   2022-04-26
52   2022-12-20
53   2024-09-09
54   2026-07-22
55   2026-03-23
56   2023-10-03
Name: transaction_date, dtype: datetime64[ns]

In [39]:
account_transactions.head(50)

,account_id,credit_score,account_status,transaction_id,transaction_date,category,transaction_type,payment_method,status
1,10357.0,734.0,Active,100002,2025-01-13,Utilities,Payment,Credit Card,Completed
2,10140.0,600.0,Active,100003,2025-08-04,Entertainment,Payment,ACH,Completed
3,10049.0,765.0,Active,100004,2022-03-28,Healthcare,Payment,Credit Card,Completed
4,10544.0,452.0,Closed,100005,2022-10-19,Payroll/Salary,Deposit,ACH,Completed
5,10415.0,307.0,Active,100006,2025-10-19,Utilities,Payment,Debit Card,Completed
6,10481.0,331.0,Active,100007,2022-09-25,Entertainment,Payment,Debit Card,Failed
7,10519.0,363.0,Active,100008,2022-09-16,Insurance,Payment,Credit Card,Completed
8,10560.0,602.0,Active,100009,2024-02-05,Insurance,Payment,Check,Completed
9,10328.0,620.0,Active,100010,2022-11-18,Dining,Withdrawal,Debit Card,Completed
10,10636.0,756.0,Active,100011,2023-01-03,Healthcare,Payment,Check,Completed
11,10437.0,335.0,Active,100012,2023-06-11,Payroll/Salary,Deposit,ACH,Completed
13,10385.0,679.0,Active,100014,2023-06-03,Healthcare,Payment,Credit Card,Completed
14,10168.0,319.0,Active,100015,2022-02-17,Fees,Fee,ACH,Failed
15,10447.0,387.0,Active,100016,2025-02-06,Utilities,Payment,Debit Card,Completed
16,10624.0,640.0,Active,100017,2024-03-11,Utilities,Payment,Check,Completed
17,10231.0,419.0,Active,100018,2024-10-26,Shopping,Payment,Debit Card,Completed
18,10249.0,659.0,Active,100019,2024-07-23,Dining,Withdrawal,Credit Card,Completed
19,10459.0,682.0,Active,100020,2023-07-15,Transfers,Transfer,ACH,Completed
20,10334.0,780.0,Closed,100021,2022-02-24,Rent,Payment,Wire Transfer,Completed
21,10061.0,837.0,Frozen,100022,2026-01-01,Healthcare,Payment,Credit Card,Completed
23,10648.0,319.0,Active,100024,2026-04-21,Entertainment,Payment,Credit Card,Completed
24,10375.0,826.0,Active,100025,2024-05-01,Insurance,Payment,Credit Card,Completed
25,10402.0,710.0,Active,100026,2023-03-27,Rent,Payment,Check,Completed
26,10065.0,753.0,Active,100027,2025-11-27,Transportation,Withdrawal,Cash,Completed
27,10458.0,573.0,Active,100028,2022-01-28,Entertainment,Payment,Credit Card,Completed
28,10648.0,319.0,Active,100029,2023-11-05,Utilities,Payment,Check,Completed
29,10513.0,568.0,Closed,100030,2024-02-21,Insurance,Payment,Credit Card,Completed
30,10271.0,714.0,Active,100031,2026-01-24,Healthcare,Payment,Credit Card,Completed
31,10293.0,696.0,Closed,100032,2024-06-22,Transportation,Withdrawal,Credit Card,Completed
33,10178.0,497.0,Active,100034,2024-09-29,Payroll/Salary,Deposit,ACH,Pending
34,10436.0,631.0,Active,100035,2024-05-18,Shopping,Withdrawal,Debit Card,Completed
36,10471.0,448.0,Active,100037,2022-07-02,Rent,Payment,NaN,Pending
38,10468.0,756.0,Active,100039,2024-04-17,Healthcare,Payment,Check,Completed
39,10260.0,312.0,Active,100040,2022-03-27,Rent,Payment,Wire Transfer,Pending
40,10042.0,555.0,Active,100041,2022-04-28,Dining,Withdrawal,Credit Card,Completed
41,10436.0,631.0,Active,100042,2024-08-31,Insurance,Payment,ACH,Completed
42,10698.0,427.0,Active,100043,2024-02-09,Transfers,Transfer,Wire Transfer,Completed
43,10463.0,611.0,Active,100044,2024-08-14,Utilities,Payment,Debit Card,Completed
45,10416.0,732.0,Active,100046,2024-06-13,Entertainment,Payment,Debit Card,Completed
46,10077.0,448.0,Closed,100047,2025-04-23,Insurance,Payment,Check,NaN
47,10402.0,710.0,Active,100048,2023-03-25,Healthcare,Payment,Credit Card,Completed
48,10197.0,315.0,Active,100049,2026-07-18,Dining,Withdrawal,Cash,Completed
49,10363.0,722.0,Closed,100050,2025-10-20,Healthcare,Payment,Debit Card,Completed
50,10447.0,387.0,Active,100051,2022-10-09,Healthcare,Payment,Credit Card,Completed
51,10545.0,400.0,Active,100052,2022-04-26,Rent,Payment,Check,Failed
52,10269.0,716.0,Active,100053,2022-12-20,Transfers,Transfer,Wire Transfer,Completed
53,10100.0,448.0,Active,100054,2024-09-09,Transfers,Deposit,Wire Transfer,Completed
54,10227.0,773.0,Active,100055,2026-07-22,Payroll/Salary,Payment,ACH,Completed
55,10361.0,460.0,Active,100056,2026-03-23,Insurance,Payment,ACH,Completed
56,10207.0,516.0,Active,100057,2023-10-03,Groceries,Payment,Credit Card,Completed

In [40]:
final_data=account_transactions.to_csv('~/Desktop/final_data.csv')